[project]
name = "sbur"
version = "0.1.0"
description = "Subtitles renamer using LLM"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["nexaai>=1.0.42"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.14.13",
]
